version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  bai-hu-docker-hub:
    image: rootthekid/bai-hu:latest
    container_name: bai-hu
    environment: 
      - MQTT_BROKER=mosquitto
    depends_on: 
      - mosquitto
    ports: 
      - 8081:3000
    restart: always
  
  xuan-wu-docker-hub:
    image: rootthekid/xuan-wu:latest
    container_name: xuan-wu
    environment: 
      - MQTT_BROKER=mosquitto
      - TADO_EMAIL=
      - TADO_PASSWORD=
      - ADDRESS=0.0.0.0
    depends_on: 
      - mosquitto
    ports: 
      - 8080:3000
    restart: always

  web:
    image: rootthekid/zhu-que:latest
    container_name: zhu-que
    depends_on: 
      - mosquitto
      - xuan-wu-docker-hub
      - bai-hu-docker-hub
    ports:
      - 80:80
    restart: always
