version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  web:
    image: registry.gitlab.com/smart-home-the-verse/433mhz-middle-man:latest
    container_name: 433mhz-middle-man
    depends_on: 
      - mosquitto
    ports:
      - 3000:80
    restart: always

  web-docker-hub:
    image: rootthekid/433mhz-middle-man:latest
    container_name: 433mhz-middle-man
    depends_on: 
      - mosquitto
    ports: 
      - 3000:80
    restart: always
